title: "XJDF"
description: "The Exchange Job Definition Format"
baseurl: "/xjdf-book/EDGE"
url: "https://meixxi.github.io"
markdown: kramdown

exclude:
  - README.md

remote_theme: just-the-docs/just-the-docs
logo: /assets/xjdf-logo.png


