title: "XJDF"
description: "The Exchange Job Definition Format"
baseurl: ${BASE_URL}
url: "https://xjdf-book.github.io"
markdown: kramdown

exclude:
  - README.md

remote_theme: just-the-docs/just-the-docs
logo: /assets/xjdf-logo.png


