name: Deploy Book

on:
  push:
    paths: ["book/**"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # define destination path (DEST_DIR)
      - name: Set Environment Variable
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "DEST_DIR=EDGE" >> $GITHUB_ENV
          else
            echo "DEST_DIR=DEV/${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Verify Variable
        run: echo "DEST_DIR is $DEST_DIR"

      # set jekyll parameters
      - name: Substitute variables in template
        run: |
          export BASE_URL=/${DEST_DIR}
          cd book
          mv _config.yml _config.tpl.yml
          envsubst < _config.tpl.yml > _config.yml
          rm _config.tpl.yml

      - name: Expose jekyll config
        run: |
          cat book/_config.yml

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./book
          destination: ./public


      # deploy pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  
          destination_dir: ${{ env.DEST_DIR }}
