name: Deploy index.html

on:
  push:
    branches: ["main"]
    paths: ["index.html"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # create public fulder
      - name: Copy index.html to public
        run: |
          mkdir -p public
          cp index.html public/

      # deploy
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  
          destination_dir: ./
          keep_files: true
