name: Deploy Book

on:
  push:
    branches: ["main"]
    # paths: ["src/**"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'

      # - name: Install markdown-cli
      #   run: npm install -g markdown-cli

      # - name: Convert Markdown to HTML
      #   run: |
      #     mkdir -p dist
      #     markdown-cli README.md > dist/index.html

      - name: Create Dummy HTML
        run: |
          mkdir -p dist
          echo "<!DOCTYPE html>" > dist/index.html
          echo "<html>" >> dist/index.html
          echo "<head><title>Dummy Page</title></head>" >> dist/index.html
          echo "<body><h1>This is a test deployment</h1></body>" >> dist/index.html
          echo "</html>" >> dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust to your build output directory
          destination_dir: SNAPSHOT
          force_orphan: true
          # force_orphan: true  # Forces the creation of a clean branch
        
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: './build'
          
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4